### PR TITLE
first pass at adding GCM support

### PR DESCRIPTION
**Pull request by dvanduzer**
I've only tested this with AES so far, and the additional authenticated
data probably isn't actually optional in this commit. I _have_ verified
that encryption/decryption works in both directions when interacting with
cryptography.io's OpenSSL backend. So that's a plus.

See https://github.com/pyca/cryptography/issues/846 if interested in other details... The _internal_ interface inconsistencies _within_ TomCrypt and OpenSSL are confusing enough as it is, but maybe you have some other ideas. The EAX header and the GCM aad can possible use the same interface, but in GCM you can't add unencrypted data after adding the encrypted payload. Details.

### CODE REVIEW

**Comment by dvanduzer** [comment]
Oh, and the user is currently responsible for validating the GCM tag. That should probably be wrapped.

I'm anticipating moving to https://github.com/pyca/cryptography/ for Python Telehash in the long run, but if you're interested in porting PyTomCrypt to be a backend provider for that project, I'd definitely help out.

**Comment by mikeboers** [comment]
Thanks for trying to tackle this! The internal API inconsistencies that you speak of are exactly the reason that I didn't do this in the first place.

Besides trying to smooth over the API, wrapping some more logic WRT the GCM tag, docs and testing, do you think there is anything else to do?

Thanks for pointing me towards @pyca's project; perhaps it could be interesting to provide a backend for them.

**Comment by dvanduzer** [comment]
I want to do some benchmarking with the table computation to be sure it's worth it over just using the simpler all-in-one call, once I find a bit more time. Then I'll write up docs/tests for the new methods needed. For that matter, if the non-table approach ends up making more sense, it might not need to change the interface at all.

**Comment by dvanduzer** [comment]
Wrapping the gcm_memory() call will require a bit more effort, so I benchmarked a rough equivalent with gcm_init() versus gcm_reset().

I've altered vendor/libtomcrypt/src/headers/tomcrypt_custom.h to shed a little more light on performance (2.13GHz Intel Core 2 Duo Macbook Air) in a couple of runs:

default build:

> (tomcrypt)[dvd@fwiffo ~/src/telehash/PyTomCrypt]$ python examples/gcm-speed.py 
> GCM using tables:
> [2.7426929473876953, 2.9673140048980713, 2.7264668941497803]
> No GCM acceleration:
> [5.3436901569366455, 5.355175018310547, 5.788615942001343]
> ECB reference:
> [2.4110639095306396, 2.423086166381836, 2.3063981533050537]

with #define LTC_NO_TABLES:

> (tomcrypt)[dvd@fwiffo ~/src/telehash/PyTomCrypt]$ python examples/gcm-speed.py 
> GCM using tables:
> [3.3719801902770996, 3.355034828186035, 3.3389339447021484]
> No GCM acceleration:
> [3.509998083114624, 3.548793077468872, 3.5203521251678467]
> ECB reference:
> [2.5642800331115723, 2.332797050476074, 2.2742910385131836]

The benchmark is pretty flawed, since "No GCM acceleration" actually means "rebuild the tables every time", but the deltas suggest a ~10% overhead by not using gcm_memory() and a ~20% speedup when using GCM tables.

A theoretically comparable test of pyca/cryptography (OpenSSL backend) is 2x-3x slower than PyTomCrypt regardless: https://gist.github.com/dvanduzer/ba762e37a70422499f9d

I'm taking the comments in https://github.com/pyca/cryptography/issues/846 pretty seriously though, and the choices I understand are "3x speedup but maybe vulnerable to timing attacks" or "2x speedup with LTC_NO_TABLES."

Beyond that, maybe the question of whether GCM should be supported on anything without hardware acceleration needs to be taken upstream? Other thoughts?

**Comment by mikeboers** [comment]
I'm sorry to leave this sitting for so long. Same excuses, real job, blah blah blah.

I'm not sure I'm 100% on all of the discussion and implications from the linked issue, but my vote is on slightly slower with less potential for timing attacks.

**Comment by dvanduzer** [comment]
That's definitely my vote too. The lesson I've taken away from the linked discussion is that it isn't immediately obvious which of any of those methods is implemented in OpenSSL or TomCrypt.

Disabling tables for GCM only in TomCrypt is possible with a minor ifdef tweak. What I'm not clear on is whether even _that_ is an implementation that "leaks timing like a sieve" or however it was put.

**Comment by mikeboers** [comment]
I've added a little bit of docs and a basic test, then merged it into master. I'm going to do a little bit of history rewriting, so let it sit for a few minutes. ;)

**Comment by mikeboers** [comment]
I unmerged it, since I want to be sure we have LTC_NO_TABLES in place first.

Going to look into modifying tomcrypt_custom.h another way.

**Comment by mikeboers** [comment]
I've set the macro in 76007ce7.

Forgive me for not taking the time to really understand what is going on, but is the `reset()` method still necessary?

**Comment by dvanduzer** [comment]
The gcm_reset() routine is a convenience for reusing GCM table structures. The other details involved with the order IV or additional auth data is added make GCM different pretty different from EAX. The **init**() might need to be differently flexible than what Mako is allowing currently. With GCM tables disabled, gcm_memory() all-in-one looks like the better choice.

(The GCM aad is sort of like EAX header data, but the implementation specifics beyond that require more in-depth discussion.)

There's another ifdef somewhere for disabling _just_ GCM tables and leaving any other tables implementation in place. That would be the most expedient way to just do this, and not worry about benchmark changes in any of the other ciphers.

**Pull request merged**
